// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eilhdzzoogkvrkkcaepc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVpbGhkenpvb2drdnJra2NhZXBjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxOTc2NTcsImV4cCI6MjA2Nzc3MzY1N30.29w6opBdyzk4EnUo4WaSSWSqF18RAjCwqtmIl6YYyGg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});